export const students = [
  { id: 1, name: "Muhriddin", status: "Web developer" },
  { id: 2, name: "Azizbek", status: ".Net developer" },
  { id: 3, name: "Og'abek", status: "Train" },
  { id: 4, name: "Begzod", status: "Sportsman" },
  { id: 5, name: "Sanat", status: "Guester" },
  { id: 6, name: "Sunnat", status: "Vue developer" },
  { id: 7, name: "Ruslan", status: "Doctor" },
];

export const data = [
  {
    id: 1,
    name: "Muhriddin ",
    age: 23,
    address: "Bukhara",
    status: "Student",
    nickname: "ZiyoWeb",
    univ: "TUIT",
    job: "Developer",
    edit: "Edit",
  },
  {
    id: 2,
    name: "Azizbek",
    age: 32,
    address: "Toshkent",
    status: "Student",
    nickname: "prince",
    univ: "TUIT",
    job: "Doctor",
    edit: "Edit",
  },
  {
    id: 3,
    name: "Begzod",
    age: 13,
    address: "Andijon",
    status: "Student",
    nickname: "Lion",
    univ: "TUIT",
    job: "Security",
    edit: "Edit",
  },
  {
    id: 4,
    name: "Sanat",
    age: 20,
    address: "Namangan",
    status: "Student",
    nickname: "Tiger",
    univ: "TUIT",
    job: "Farmer",
    edit: "Edit",
  },
  {
    id: 5,
    name: "Bahriddin",
    age: 14,
    address: "Sirdaryo",
    status: "Student",
    nickname: "ZiyoWeb",
    univ: "TUIT",
    job: "Developer",
    edit: "Edit",
  },
  {
    id: 6,
    name: "Ikrom",
    age: 63,
    address: "Surxondaryo",
    status: "Student",
    nickname: "ZiyoWeb",
    univ: "TUIT",
    job: "Developer",
    edit: "Edit",
  },
  {
    id: 7,
    name: "Javohir",
    age: 37,
    address: "Qoraqalpog'iston",
    status: "Student",
    nickname: "prince",
    univ: "TUIT",
    job: "Developer",
    edit: "Edit",
  },
  {
    id: 8,
    name: "Feruz",
    age: 10,
    address: "Samarqand",
    status: "Student",
    nickname: "ZiyoWeb",
    univ: "TUIT",
    job: "Developer",
    edit: "Edit",
  },
  {
    id: 9,
    name: "Ruslan",
    age: 41,
    address: "Jizzax",
    status: "Student",
    nickname: "ZiyoWeb",
    univ: "TUIT",
    job: "Developer",
    edit: "Edit",
  },
  {
    id: 10,
    name: "Mamur",
    age: 22,
    address: "Qarshi",
    status: "Student",
    nickname: "ZiyoWeb",
    univ: "TUIT",
    job: "Developer",
    edit: "Edit",
  },
  {
    id: 11,
    name: "Sunnat",
    age: 23,
    address: "Xorazm",
    status: "Student",
    nickname: "ZiyoWeb",
    univ: "TUIT",
    job: "Developer",
    edit: "Edit",
  },
  {
    id: 12,
    name: "Shahzod",
    age: 65,
    address: "Bukhara, Vabkent",
    status: "Student",
    nickname: "ZiyoWeb",
    univ: "TUIT",
    job: "Developer",
    edit: "Edit",
  },
  {
    id: 13,
    name: "Xushnud",
    age: 57,
    address: "Bukhara",
    status: "Student",
    nickname: "ZiyoWeb",
    univ: "TUIT",
    job: "Developer",
    edit: "Edit",
  },
  {
    id: 14,
    name: "Zikrillo",
    age: 76,
    address: "Navoiy",
    status: "Student",
    nickname: "yoWeb",
    univ: "TATU",
    job: "Developer",
    edit: "Edit",
  },
  {
    id: 15,
    name: "Umid",
    age: 11,
    address: "Bukhara",
    status: "Worker",
    nickname: "oWeb",
    univ: "TUIT",
    job: "no job",
    edit: "Edit",
  },
];
